const suggestionPages = [
  {
    suggestionTitle:
      "People who are in the Technology, Information and Internet industry also follow these people",
    "data-type": "tech",
  },
  { suggestionTitle: "Groups you may be interested in", "data-type": "groups" },
  {
    suggestionTitle: "Popular people to follow across LinkedIn",
    "data-type": "popPeople",
  },
  { suggestionTitle: "More suggestions for you", "data-type": "morePeople" },
];

const techRecommendedData = [
  {
    username: "Adam Vegam",
    "cover-image": "cover-1.jpg",
    "profile-image": "profile1.jpg",
    about: "Software Developer | @Google| Learner",
    followerCount: 2345,
  },
  {
    username: "Keth Janifer",
    "cover-image": "cover-2.jpg",
    "profile-image": "profile2.jpg",
    about: "FrontEnd Developer, USA,Freelencer",
    followerCount: 4673,
  },
  {
    username: "Jonathon Kover",
    "cover-image": "cover-3.jpg",
    "profile-image": "profile3.jpg",
    about: "Graphic Designer, PS, Ae ",
    followerCount: 23056,
  },
  {
    username: "Kristina Gorge",
    "cover-image": "cover-4.jpg",
    "profile-image": "profile4.jpg",
    about: "Video editor | Youtuber",
    followerCount: 7832,
  },
  {
    username: "Novem Sover",
    "cover-image": "cover-5.jpg",
    "profile-image": "profile5.jpg",
    about: "Ethical Hacker @hackerPoint.com",
    followerCount: 1257,
  },
  {
    username: "Lomam Thover",
    "cover-image": "cover-6.jpg",
    "profile-image": "profile6.jpg",
    about: "Embeded Software Developer",
    followerCount: 9805,
  },
];

const groupsData = [
  {
    username: "Tech Master",
    "cover-image": "cover-1.jpg",
    "profile-image": "profile1.jpg",
    about: "Software Developer | @Google|",
    followerCount: 2345,
    buttonText: "Join",
  },
  {
    username: "Geeks for Geeks",
    "cover-image": "cover-2.jpg",
    "profile-image": "profile2.jpg",
    about: "FrontEnd Developer, USA,Freelencer",
    followerCount: 4673,
    buttonText: "Join",
  },
  {
    username: "Imagine",
    "cover-image": "cover-3.jpg",
    "profile-image": "profile3.jpg",
    about: "Graphic Designer, PS, Ae ",
    followerCount: 23056,
    buttonText: "Join",
  },

  {
    username: "Developers",
    "cover-image": "cover-5.jpg",
    "profile-image": "profile5.jpg",
    about: "Ethical Hacker @hackerPoint.com",
    followerCount: 1257,
    buttonText: "Join",
  },
  {
    username: "Solve Error",
    "cover-image": "cover-5.jpg",
    "profile-image": "profile5.jpg",
    about: "Ethical Hacker @hackerPoint.com",
    followerCount: 1257,
    buttonText: "Join",
  },
  {
    username: "Connection",
    "cover-image": "cover-6.jpg",
    "profile-image": "profile6.jpg",
    about: "Embeded Software Developer",
    followerCount: 9805,
    buttonText: "Join",
  },
];

const popularPeoplesData = [
  {
    username: "Sandeep Lamichhane",
    "cover-image": "cover-1.jpg",
    "profile-image": "profile1.jpg",
    about: "Software Developer | @Google| Learner",
    followerCount: 2345,
  },
  {
    username: "The Rock",
    "cover-image": "cover-2.jpg",
    "profile-image": "profile2.jpg",
    about: "FrontEnd Developer, USA,Freelencer",
    followerCount: 4673,
  },

  {
    username: "Mahesh Babu",
    "cover-image": "cover-5.jpg",
    "profile-image": "profile5.jpg",
    about: "Ethical Hacker @hackerPoint.com",
    followerCount: 1257,
  },
  {
    username: "Akshay Kumar",
    "cover-image": "cover-6.jpg",
    "profile-image": "profile6.jpg",
    about: "Embeded Software Developer",
    followerCount: 9805,
  },

  {
    username: "Prabhas",
    "cover-image": "cover-6.jpg",
    "profile-image": "profile6.jpg",
    about: "Embeded Software Developer",
    followerCount: 9805,
  },
  {
    username: "Vin Diesel",
    "cover-image": "cover-6.jpg",
    "profile-image": "profile6.jpg",
    about: "Embeded Software Developer",
    followerCount: 9805,
  },
];

const morePeopleData = [
  {
    username: "Bill Gates",
    "cover-image": "cover-1.jpg",
    "profile-image": "profile1.jpg",
    about: "Software Developer | @Google| Learner",
    followerCount: 2345,
  },
  {
    username: "Mark Zuckerburg",
    "cover-image": "cover-3.jpg",
    "profile-image": "profile3.jpg",
    about: "Graphic Designer, PS, Ae ",
    followerCount: 23056,
  },
  {
    username: "Sundar Pichai",
    "cover-image": "cover-2.jpg",
    "profile-image": "profile2.jpg",
    about: "FrontEnd Developer, USA,Freelencer",
    followerCount: 4673,
  },
  {
    username: "Narendra Modi",
    "cover-image": "cover-5.jpg",
    "profile-image": "profile5.jpg",
    about: "Ethical Hacker @hackerPoint.com",
    followerCount: 1257,
  },
  {
    username: "Elon Musk",
    "cover-image": "cover-3.jpg",
    "profile-image": "profile3.jpg",
    about: "Graphic Designer, PS, Ae ",
    followerCount: 23056,
  },
  {
    username: "Kamal Hasan",
    "cover-image": "cover-3.jpg",
    "profile-image": "profile3.jpg",
    about: "Graphic Designer, PS, Ae ",
    followerCount: 23056,
  },

  {
    username: "Narendra Modi",
    "cover-image": "cover-5.jpg",
    "profile-image": "profile5.jpg",
    about: "Ethical Hacker @hackerPoint.com",
    followerCount: 1257,
  },
  {
    username: "Shah Rukh Khan",
    "cover-image": "cover-5.jpg",
    "profile-image": "profile5.jpg",
    about: "Ethical Hacker @hackerPoint.com",
    followerCount: 1257,
  },
  {
    username: "Prabhas",
    "cover-image": "cover-6.jpg",
    "profile-image": "profile6.jpg",
    about: "Embeded Software Developer",
    followerCount: 9805,
  },
  {
    username: "Ram charan",
    "cover-image": "cover-6.jpg",
    "profile-image": "profile6.jpg",
    about: "Embeded Software Developer",
    followerCount: 9805,
  },
  {
    username: "Tony Stark",
    "cover-image": "cover-6.jpg",
    "profile-image": "profile6.jpg",
    about: "Embeded Software Developer",
    followerCount: 9805,
  },
  {
    username: "Salman Khan",
    "cover-image": "cover-6.jpg",
    "profile-image": "profile6.jpg",
    about: "Embeded Software Developer",
    followerCount: 9805,
  },
];

const seeAllTechRecom = [
  {
    username: "Adam Vegam",
    "cover-image": "cover-1.jpg",
    "profile-image": "profile1.jpg",
    about: "Software Developer | @Google| Learner",
    followerCount: 2345,
  },
  {
    username: "Bill Gates",
    "cover-image": "cover-1.jpg",
    "profile-image": "profile1.jpg",
    about: "Software Developer | @Google| Learner",
    followerCount: 2345,
  },
  {
    username: "Mark Zuckerburg",
    "cover-image": "cover-3.jpg",
    "profile-image": "profile3.jpg",
    about: "Graphic Designer, PS, Ae ",
    followerCount: 23056,
  },
  {
    username: "Sundar Pichai",
    "cover-image": "cover-2.jpg",
    "profile-image": "profile2.jpg",
    about: "FrontEnd Developer, USA,Freelencer",
    followerCount: 4673,
  },
  {
    username: "Elon Musk",
    "cover-image": "cover-3.jpg",
    "profile-image": "profile3.jpg",
    about: "Graphic Designer, PS, Ae ",
    followerCount: 23056,
  },
  {
    username: "Keth Janifer",
    "cover-image": "cover-2.jpg",
    "profile-image": "profile2.jpg",
    about: "FrontEnd Developer, USA,Freelencer",
    followerCount: 4673,
  },
  {
    username: "Jonathon Kover",
    "cover-image": "cover-3.jpg",
    "profile-image": "profile3.jpg",
    about: "Graphic Designer, PS, Ae ",
    followerCount: 23056,
  },
  {
    username: "Kristina Gorge",
    "cover-image": "cover-4.jpg",
    "profile-image": "profile4.jpg",
    about: "Video editor | Youtuber",
    followerCount: 7832,
  },
  {
    username: "Technical Guruji",
    "cover-image": "cover-5.jpg",
    "profile-image": "profile5.jpg",
    about: "Ethical Hacker @hackerPoint.com",
    followerCount: 1257,
  },
  {
    username: "Tony Stark",
    "cover-image": "cover-6.jpg",
    "profile-image": "profile6.jpg",
    about: "Embeded Software Developer",
    followerCount: 9805,
  },
  {
    username: "Lomam Thover",
    "cover-image": "cover-6.jpg",
    "profile-image": "profile6.jpg",
    about: "Embeded Software Developer",
    followerCount: 9805,
  },
  {
    username: "Imagine",
    "cover-image": "cover-3.jpg",
    "profile-image": "profile3.jpg",
    about: "Graphic Designer, PS, Ae ",
    followerCount: 23056,
  },

  {
    username: "Tech Burner",
    "cover-image": "cover-5.jpg",
    "profile-image": "profile5.jpg",
    about: "Ethical Hacker @hackerPoint.com",
    followerCount: 1257,
  },
  {
    username: "RajKumar Aryan",
    "cover-image": "cover-3.jpg",
    "profile-image": "profile3.jpg",
    about: "Graphic Designer, PS, Ae ",
    followerCount: 23056,
  },
  {
    username: "Aman Gupta",
    "cover-image": "cover-2.jpg",
    "profile-image": "profile2.jpg",
    about: "Founder of Boat",
    followerCount: 4673,
  },
];

const seeAllGroupsRecom = [
  {
    username: "Tech Master",
    "cover-image": "cover-1.jpg",
    "profile-image": "profile1.jpg",
    about: "Software Developer | @Google|",
    followerCount: 2345,
    buttonText: "Join",
  },
  {
    username: "Geeks for Geeks",
    "cover-image": "cover-2.jpg",
    "profile-image": "profile2.jpg",
    about: "FrontEnd Developer, USA,Freelencer",
    followerCount: 4673,
    buttonText: "Join",
  },
  {
    username: "Imagine",
    "cover-image": "cover-3.jpg",
    "profile-image": "profile3.jpg",
    about: "Graphic Designer, PS, Ae ",
    followerCount: 23056,
    buttonText: "Join",
  },

  {
    username: "Developers",
    "cover-image": "cover-5.jpg",
    "profile-image": "profile5.jpg",
    about: "Ethical Hacker @hackerPoint.com",
    followerCount: 1257,
    buttonText: "Join",
  },
  {
    username: "Solve Error",
    "cover-image": "cover-5.jpg",
    "profile-image": "profile5.jpg",
    about: "Ethical Hacker @hackerPoint.com",
    followerCount: 1257,
    buttonText: "Join",
  },
  {
    username: "Connection",
    "cover-image": "cover-6.jpg",
    "profile-image": "profile6.jpg",
    about: "Embeded Software Developer",
    followerCount: 9805,
    buttonText: "Join",
  },
  {
    username: "Developers",
    "cover-image": "cover-5.jpg",
    "profile-image": "profile5.jpg",
    about: "Ethical Hacker @hackerPoint.com",
    followerCount: 1257,
    buttonText: "Join",
  },
  {
    username: "Solve Error",
    "cover-image": "cover-5.jpg",
    "profile-image": "profile5.jpg",
    about: "Ethical Hacker @hackerPoint.com",
    followerCount: 1257,
    buttonText: "Join",
  },
  {
    username: "Connection",
    "cover-image": "cover-6.jpg",
    "profile-image": "profile6.jpg",
    about: "Embeded Software Developer",
    followerCount: 9805,
    buttonText: "Join",
  },
];
